### ISSUE TITLE
App crash após pagamento.

### ISSUE THREAD

**Issue by WBlackstorm** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#49]
Bom dia.
Estamos tomando um erro na LIO após o pagamento ser confirmado e a aplicação voltar para foreground. 
Esse erro não ocorreu com o emulador da LIO.
Abaixo segue o log capturado no crashlytics.

`Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=cielo.sdk.ON_PAYMENT flg=0x10 pkg=br.com.wstorm.bpay (has extras) } in b.b.b.g.a$b@d590178
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:932)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

`Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: cielo.orders.aidl.ParcelableOrder
       at android.os.Parcel.readParcelableCreator(Parcel.java:2411)
       at android.os.Parcel.readParcelable(Parcel.java:2337)
       at android.os.Parcel.readValue(Parcel.java:2243)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.Bundle.getParcelable(Bundle.java:786)
       at android.content.Intent.getParcelableExtra(Intent.java:5575)
       at cielo.sdk.order.v1.OrderManagerImplv1$PaymentBroadcastReceiver.onReceive(OrderManagerImplv1.java)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:922)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

**Comment by dcrec1** [comment]
Você chegou a encontrar o problema?
