### ISSUE TITLE
Emulador LIO não é detectado ao chamar OrderManager

### ISSUE THREAD

**Issue by gabriel-amorim** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#60]
Conforme a documentação e a orientação informada na issue [#13](https://github.com/DeveloperCielo/LIO-SDK-Sample-Integracao-Local/issues/13), é necessária a instalação do emulador LIO para a utilização em outros dispositivos.

Possuo o emulador instalado e consigo abri-lo normalmente, no entanto, ao chamar OrderManager ocorre a exceção abaixo.

```
     Caused by: android.content.pm.PackageManager$NameNotFoundException: cielo.launcher
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:293)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:265)
        at cielo.sdk.order.OrderManager.<init>(OrderManager.kt:43)
```

**Comment by romaia** [comment]
Tive o mesmo problema, e encontrei a solução aqui:

https://stackoverflow.com/questions/64819384/android-content-pm-packagemanagernamenotfoundexception-com-android-chrome

O problema acontece com versões mais recentes do android, onde é preciso colocar isso no manifest:

```
 <manifest package="com.example.app">
   <queries>
      <package android:name="cielo.launcher" />
    </queries>
 </manifest>
```
